workflows:
  android-liberty-vpn:
    name: Liberty VPN Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "io.nekohasekai.sagerenet"
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: |
          ./gradlew :app:assembleOssDebug -Dorg.gradle.jvmargs="--add-opens=java.base/java.lang=ALL-UNNAMED"
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - timalajf012@gmail.com
        notified:
          on_success: true
          on_failure: true
